import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';
import { eq } from 'drizzle-orm';
import { db } from '../db/index.js';
import { session, oneTimeAuthCodes } from '../db/schema.js';
import { logger } from './error-handler.js';

/**
 * WebKit ITP / Cross-Site Cookie Workaround Middleware
 *
 * WHY THIS EXISTS:
 * Safari (and WebKit-based browsers on iOS/macOS, as well as Brave with strict shields)
 * blocks 3rd-party/cross-site cookies set during OAuth redirect chains (ITP - Intelligent Tracking Prevention).
 * When Better Auth attempts to set `better-auth.session_token` on the OAuth callback redirect response,
 * WebKit discards the Set-Cookie header or ignores the cookie on subsequent requests.
 *
 * HOW IT WORKS:
 * 1. This middleware intercepts responses on `/api/auth/callback/*`.
 * 2. It sniffs the `Set-Cookie` header generated by Better Auth to extract the session token.
 * 3. Instead of redirecting directly to `/` or the app frontend with a cookie that WebKit will drop,
 *    it generates a secure 32-byte one-time authentication code and stores it in `one_time_auth_codes`.
 * 4. It redirects the browser to `/auth/complete?code=<one-time-code>`.
 * 5. The frontend then calls `POST /api/auth/complete-login` with the code to exchange it for a
 *    Same-Origin session cookie and JSON session payload.
 *
 * DO NOT DELETE THIS MIDDLEWARE: Removing it will break OAuth login for Safari, iOS Expo WebViews, and Brave users.
 */

const SESSION_COOKIE_RE = /(?:^|[\s;,])((?:__Secure-)?(?:better-auth|baari)\.session_token)=([^;]+)/;

/** Signed cookie value is "<token>.<signature>"; DB stores only "<token>". */
export const rawTokenFromCookieValue = (value: string): string => {
  let v = value;
  try {
    v = decodeURIComponent(v);
  } catch (_) {}
  return v.replace(/^["']|["']$/g, '').split('.')[0].trim();
};

export function oauthCallbackInterceptor(req: Request, res: Response, next: NextFunction): void {
  // Re-inject the OAuth state cookie from ?state= (plain + __Secure- names)
  if (typeof req.query.state === 'string' && req.query.state) {
    const existing = req.headers.cookie || '';
    if (!/(?:^|;\s*)(?:__Secure-)?better-auth\.state=/.test(existing)) {
      const extra = `better-auth.state=${req.query.state}; __Secure-better-auth.state=${req.query.state}`;
      req.headers.cookie = existing ? `${existing}; ${extra}` : extra;
      logger.info({ msg: 'Injected OAuth state cookie from query parameter' });
    }
  }

  let capturedCookieValue: string | null = null;
  const captureFrom = (setCookie: unknown) => {
    if (!setCookie) return;
    const list = Array.isArray(setCookie) ? setCookie : [String(setCookie)];
    for (const c of list) {
      const m = String(c).match(SESSION_COOKIE_RE);
      if (m?.[2]) capturedCookieValue = m[2];
    }
  };

  const originalSetHeader = res.setHeader.bind(res);
  res.setHeader = ((name: string, value: any) => {
    if (name.toLowerCase() === 'set-cookie') captureFrom(value);
    return originalSetHeader(name, value);
  }) as typeof res.setHeader;

  const isMobileRedirect = (loc: string) =>
    Boolean(req.headers['expo-origin']) ||
    loc.startsWith('baari://') ||
    loc.startsWith('exp://') ||
    !/^https?:\/\//i.test(loc);

  const originalWriteHead = res.writeHead.bind(res) as any;
  (res as any).writeHead = (statusCode: number, ...rest: any[]) => {
    let statusMessage: string | undefined;
    let headers: any;
    if (typeof rest[0] === 'string') {
      statusMessage = rest[0];
      headers = rest[1];
    } else {
      headers = rest[0];
    }

    let location: string | undefined;
    const readHeaders = (h: any) => {
      if (!h) return;
      if (Array.isArray(h)) {
        if (h.length && Array.isArray(h[0])) {
          for (const [k, v] of h) {
            if (String(k).toLowerCase() === 'location') location = String(v);
            if (String(k).toLowerCase() === 'set-cookie') captureFrom(v);
          }
        } else {
          for (let i = 0; i + 1 < h.length; i += 2) {
            if (String(h[i]).toLowerCase() === 'location') location = String(h[i + 1]);
            if (String(h[i]).toLowerCase() === 'set-cookie') captureFrom(h[i + 1]);
          }
        }
      } else {
        for (const k of Object.keys(h)) {
          if (k.toLowerCase() === 'location') location = String(h[k]);
          if (k.toLowerCase() === 'set-cookie') captureFrom(h[k]);
        }
      }
    };
    readHeaders(headers);
    if (!location) {
      const l = res.getHeader('location');
      if (l) location = String(l);
    }
    captureFrom(res.getHeader('set-cookie'));

    const isRedirect = statusCode >= 300 && statusCode < 400 && !!location;

    if (isRedirect && location) {
      if (location.includes('error=')) {
        logger.error({ msg: 'OAuth callback redirected with error', location, query: req.query });
      } else if (isMobileRedirect(location)) {
        logger.info({ msg: 'Passing through mobile OAuth redirect', location });
      } else if (capturedCookieValue) {
        const cookieValue = capturedCookieValue;
        const rawToken = rawTokenFromCookieValue(cookieValue);
        const loc = location;
        (async () => {
          try {
            const sessRows = await db
              .select({ userId: session.userId })
              .from(session)
              .where(eq(session.token, rawToken))
              .limit(1);

            if (!sessRows.length) throw new Error('session row not found for callback token');

            const code = crypto.randomBytes(32).toString('hex');
            await db.insert(oneTimeAuthCodes).values({
              code,
              userId: sessRows[0].userId,
              sessionToken: decodeURIComponent(cookieValue),
              expiresAt: new Date(Date.now() + 60_000),
            });

            const origin = new URL(loc).origin;
            const completionUrl = `${origin}/auth/complete?code=${code}`;
            logger.info({ msg: 'One-time auth code created for OAuth callback', completionUrl: `${origin}/auth/complete` });
            res.removeHeader('Set-Cookie');
            res.removeHeader('set-cookie');
            originalSetHeader('Location', completionUrl);
            originalWriteHead(302, { Location: completionUrl, 'Cache-Control': 'no-store' });
            res.end();
          } catch (err: any) {
            logger.error({ msg: 'One-time code handoff failed; using original redirect', error: err?.message });
            originalWriteHead(statusCode, ...(statusMessage ? [statusMessage] : []), headers);
            res.end();
          }
        })();
        return res;
      }
    }

    return statusMessage !== undefined
      ? originalWriteHead(statusCode, statusMessage, headers)
      : originalWriteHead(statusCode, headers);
  };

  next();
}
